tasks:
  - name: Start Preview server
    init: make prepare # runs during prebuild
    command: |
      make run &
      gp preview "4242-$GITPOD_WORKSPACE_URL/doc/book/installing/docker/"
    openMode: tab-before

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4242

vscode:
  extensions:
    - asciidoctor.asciidoctor-vscode
    - streetsidesoftware.code-spell-checker
